version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Build Dependencies
          command: |
            pip install -e .
            pip install flake8 pytest | cat; test ${PIPESTATUS[0]} -eq 0
            mkdir test-reports | cat
      - run:
          name: Flake8
          command: |
            flake8 . --statistics --show-source --ignore=F401,F821,I100,W503 -v
      - run:
          name: Run API Tests
          command: |
            cd ./galaxy_ml
            python -m pytest ./tests -sv
      - store_test_results:
          path: test-reports
  tool_lint:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Tool Linter
          command: |
            pip install planemo
            cd galaxy_ml/tools
            planemo lint
  tool_test:
    docker:
      - image: cimg/python:3.12
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Build Environment
          command: |
            pip install planemo
            python -m venv .venv-tool-tests
            .venv-tool-tests/bin/python -m pip install -e .
            .venv-tool-tests/bin/python scripts/configure_tool_test_dependencies.py
      - run:
          name: Tool Tests
          command: |
            cd galaxy_ml/tools
            TESTFILES=$(ls -I "*macros.xml" | grep .xml | circleci tests split)
            planemo test --dependency_resolvers_config_file ../../.planemo-local/dependency_resolvers.xml ${TESTFILES}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tool_lint
      - tool_test
